name: Main

on:
  push:
    branches: [ main ]

env:
  PROJECT_NAME: Microya-Kotlin


jobs:

  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Detekt
        run: ./gradlew detekt

  android-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Android Lint
        run: ./gradlew lintDebug

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Java classes
        uses: actions/upload-artifact@v2
        with:
          name: java-classes
          path: microya/build/intermediates/javac/debug

      - name: Upload Kotlin classes
        uses: actions/upload-artifact@v2
        with:
          name: kotlin-classes
          path: microya/build/tmp/kotlin-classes/debug

      - name: Upload Unit Tests Exec File
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-exec
          path: microya/build/jacoco/testDebugUnitTest.exec

  integration-tests:
    runs-on: macos-latest
    env:
      IMGUR_API_KEY: ${{ secrets.IMGUR_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Start Emulatur & Run UI tests
        uses: ReactiveCircus/android-emulator-runner@v2.23.0
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest