name: Main

on:
  push:
    branches: [ main ]

env:
  PROJECT_NAME: Microya-Kotlin

jobs:

  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Detekt
        run: ./gradlew detekt

  android-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Android Lint
        run: ./gradlew lintDebug

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Java classes
        uses: actions/upload-artifact@v2
        with:
          name: java-classes
          path: microya/build/intermediates/javac/debug

      - name: Upload Kotlin classes
        uses: actions/upload-artifact@v2
        with:
          name: kotlin-classes
          path: microya/build/tmp/kotlin-classes/debug

      - name: Upload Unit Tests Exec File
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-exec
          path: microya/build/jacoco/testDebugUnitTest.exec

  integration-tests:
    runs-on: [ self-hosted, macOS, arm64 ]

    steps:
      - uses: actions/checkout@v2

      - name: Start Emulatur & Run Integration tests
        run: |
          adb -s emulator-5554 emu kill > /dev/null 2>&1 &
          $ANDROID_HOME/emulator/emulator -avd PIXEL_XL_API_30 -no-boot-anim -no-audio -no-snapshot > /dev/null 2>&1 &
          ./gradlew connectedDebugAndroidTest

      - name: Stop Emulator
        if: always()
        run: adb -s emulator-5554 emu kill > /dev/null 2>&1 &

      - name: Upload Integration Tests Exec File
        uses: actions/upload-artifact@v2
        with:
          name: integration-tests-exec
          path: microya/build/outputs/code_coverage/debugAndroidTest/connected/**/*.ec

